apiVersion: v1
kind: Pod
metadata:
  name: type-demo
spec:
  containers:
  - name: k8s-demo
    image: registry.k8s.io/liveness
    ports:
    - containerPort: 8080
    
    # HTTP PROBE
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
      
    # EXEC PROBE (Check if a specific config exists)
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5
